---
name: "Facebook Notifications"
guid: "0df52034-4b59-443f-ac40-1d3f5107e2da"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Get notifications via Facebook"
description: >
  Get notifications via Facebook.
category: "Notifications"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.Facebook.dll"
changelog: >
  changelog
