---
name: "Facebook"
guid: "0df52034-4b59-443f-ac40-1d3f5107e2da"
version: "3.0.0.0"
targetAbi: "10.7.7.0"
framework: "net5.0"
overview: "Send notifications to Facebook"
description: >
  Send notifications to Facebook
category: "Notifications"
owner: "cgnetwork"
artifacts:
- "Jellyfin.Plugin.Facebook.dll"
changelog: >
  changelog